# PIPELINE DEFINITION
# Name: train-model-pipeline
# Inputs:
#    X_train_input: system.Dataset
#    X_val_input: system.Dataset
#    eval_metric: str [Default: 'rmse']
#    learning_rate: float [Default: 0.1]
#    max_depth: int [Default: 6.0]
#    min_child_weight: int [Default: 1.0]
#    n_estimators: int [Default: 300.0]
#    objective: str [Default: 'reg:squarederror']
#    y_train_input: system.Dataset
#    y_val_input: system.Dataset
# Outputs:
#    evaluate-metrics_output: system.Metrics
components:
  comp-evaluate:
    executorLabel: exec-evaluate
    inputDefinitions:
      artifacts:
        y_pred_input:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_true_input:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
      parameters:
        tag_prefix:
          parameterType: STRING
    outputDefinitions:
      artifacts:
        metrics_output:
          artifactType:
            schemaTitle: system.Metrics
            schemaVersion: 0.0.1
      parameters:
        Output:
          parameterType: NUMBER_DOUBLE
  comp-predict:
    executorLabel: exec-predict
    inputDefinitions:
      artifacts:
        X_input:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        model_input:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
    outputDefinitions:
      artifacts:
        y_output:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
  comp-train-model:
    executorLabel: exec-train-model
    inputDefinitions:
      artifacts:
        X_train_input:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        X_val_input:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_train_input:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
        y_val_input:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
      parameters:
        eval_metric:
          defaultValue: rmse
          isOptional: true
          parameterType: STRING
        learning_rate:
          defaultValue: 0.1
          isOptional: true
          parameterType: NUMBER_DOUBLE
        max_depth:
          defaultValue: 6.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        min_child_weight:
          defaultValue: 1.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        n_estimators:
          defaultValue: 300.0
          isOptional: true
          parameterType: NUMBER_INTEGER
        objective:
          defaultValue: reg:squarederror
          isOptional: true
          parameterType: STRING
    outputDefinitions:
      artifacts:
        model_output:
          artifactType:
            schemaTitle: system.Model
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-evaluate:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - evaluate
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'pandas>=2.2.3'\
          \ 'scikit-learn>=1.5.2' 'cloudml-hypertune==0.1.0.dev6' 'google-cloud-logging>=3.11.3'\
          \ && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: europe-west3-docker.pkg.dev/ml-spec-demo2/blackfriday-pipeline/evaluate_component:latest
    exec-predict:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - predict
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'pandas>=2.2.3'\
          \ 'xgboost>=2.1.2' 'joblib>=1.4.2' 'git+https://github.com/jindrvo1/blackfriday'\
          \ && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: europe-west3-docker.pkg.dev/ml-spec-demo2/blackfriday-pipeline/predict_component:latest
    exec-train-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'pandas>=2.2.3'\
          \ 'xgboost>=2.1.2' 'scikit-learn>=1.5.2' 'git+https://github.com/jindrvo1/blackfriday'\
          \ 'cloudml-hypertune==0.1.0.dev6' && \"$0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: europe-west3-docker.pkg.dev/ml-spec-demo2/blackfriday-pipeline/train_model_component:latest
pipelineInfo:
  name: train-model-pipeline
root:
  dag:
    outputs:
      artifacts:
        evaluate-metrics_output:
          artifactSelectors:
          - outputArtifactKey: metrics_output
            producerSubtask: evaluate
    tasks:
      evaluate:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-evaluate
        dependentTasks:
        - predict
        inputs:
          artifacts:
            y_pred_input:
              taskOutputArtifact:
                outputArtifactKey: y_output
                producerTask: predict
            y_true_input:
              componentInputArtifact: y_val_input
          parameters:
            tag_prefix:
              runtimeValue:
                constant: ''
        taskInfo:
          name: evaluate
      predict:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-predict
        dependentTasks:
        - train-model
        inputs:
          artifacts:
            X_input:
              componentInputArtifact: X_val_input
            model_input:
              taskOutputArtifact:
                outputArtifactKey: model_output
                producerTask: train-model
        taskInfo:
          name: predict
      train-model:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-model
        inputs:
          artifacts:
            X_train_input:
              componentInputArtifact: X_train_input
            X_val_input:
              componentInputArtifact: X_val_input
            y_train_input:
              componentInputArtifact: y_train_input
            y_val_input:
              componentInputArtifact: y_val_input
          parameters:
            eval_metric:
              componentInputParameter: eval_metric
            learning_rate:
              componentInputParameter: learning_rate
            max_depth:
              componentInputParameter: max_depth
            min_child_weight:
              componentInputParameter: min_child_weight
            n_estimators:
              componentInputParameter: n_estimators
            objective:
              componentInputParameter: objective
        taskInfo:
          name: train-model
  inputDefinitions:
    artifacts:
      X_train_input:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
      X_val_input:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
      y_train_input:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
      y_val_input:
        artifactType:
          schemaTitle: system.Dataset
          schemaVersion: 0.0.1
    parameters:
      eval_metric:
        defaultValue: rmse
        isOptional: true
        parameterType: STRING
      learning_rate:
        defaultValue: 0.1
        isOptional: true
        parameterType: NUMBER_DOUBLE
      max_depth:
        defaultValue: 6.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      min_child_weight:
        defaultValue: 1.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      n_estimators:
        defaultValue: 300.0
        isOptional: true
        parameterType: NUMBER_INTEGER
      objective:
        defaultValue: reg:squarederror
        isOptional: true
        parameterType: STRING
  outputDefinitions:
    artifacts:
      evaluate-metrics_output:
        artifactType:
          schemaTitle: system.Metrics
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.7.0
